domains
disease,indiactionname=symabol
predicates
hypothesis(name,disease)
symptom(name,indication)
clauses
symptom(amit,fever).
symptom(amit,rash).
symptom(amit,headache).
symptom(amit,runn_nose).
symptom(ajay,chills).
symptom(ajay,fever).
symptom(ajay,headache).
symptom(akshay,runny_nose).
symptom(akshay,rash).
symptom(akshay,flu).
hypothesis(P,measels):-

symptom(patient,fever),
symptom(patient,cough),
symptom(patient,conjunctivitis),
symptom(patient,rash).
hypothesis(P,german_measels):-
symptom(patient,fever),
symptom(patient,headache),
symptom(patient,runny_nose),
symptom(patient,rash).
hypothesis(P,flu):-
symptom(patient,fever),
symptom(patient,chills),
symptom(patient,headache),
symptom(patient,body_ache).
hypothesis(P,comman_cold):-
symptom(patient,fever),
symptom(patient,sneezing),
symptom(patient,sore_throat),
symptom(patient,runny_nose).
hypothesis(P,mumps):-
symptom(patient,fever),
symptom(patient,swollen_glands).


hypothesis(P,chicken_pox):-
symptom(patient,fever),
symptom(patient,rash),
symptom(patient,body_ache),
symptom(patient,chills).